name: Build
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'v*'
env:
  node_version: "12.x"

jobs:
  build: # make sure build/ci work properly
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: yarn run pack
        run: yarn run pack

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: yarn audit
        run: yarn audit --level critical [[ $? -ge 16 ]] && exit 1 || exit 0 # this last part is needed because yarn audit returns a non-0 code if any vulnerabilities are found

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: yarn install
        run: yarn install

      - name: yarn lint
        run: yarn lint

  test-code:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: yarn install
        run: yarn install

      - name: yarn test
        run: yarn test

  test-action: # make sure the action works on a clean machine without building
    name: Test normal use
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          maven-master-password: fake-master-password
      - run: cat $HOME/.m2/settings.xml
      - run: cat $HOME/.m2/settings-security.xml
