name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - v1
      - 'releases/*'

jobs:
  build: # make sure build/ci works properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn install
        yarn all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        maven-master-password: fake-master-password
    - run: cat $HOME/.m2/settings.xml
    - run: cat $HOME/.m2/settings-security.xml